-- MySQL Script generated by MySQL Workbench
-- 08/31/18 14:36:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`PESSOA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PESSOA` (
  `ID_PESSOA` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(50) NOT NULL,
  `DOCUMENTO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_PESSOA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMINENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMINENTE` (
  `ID_EMINENTE` INT(11) NOT NULL AUTO_INCREMENT,
  `PESSOA_ID_PESSOA` INT(11) NOT NULL,
  PRIMARY KEY (`ID_EMINENTE`, `PESSOA_ID_PESSOA`),
  INDEX `fk_EMINENTE_PESSOA1_idx` (`PESSOA_ID_PESSOA` ASC),
  CONSTRAINT `fk_EMINENTE_PESSOA1`
    FOREIGN KEY (`PESSOA_ID_PESSOA`)
    REFERENCES `mydb`.`PESSOA` (`ID_PESSOA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRESTADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRESTADOR` (
  `ID_PRESTADOR` INT(11) NOT NULL AUTO_INCREMENT,
  `PESSOA_ID_PESSOA` INT(11) NOT NULL,
  PRIMARY KEY (`ID_PRESTADOR`, `PESSOA_ID_PESSOA`),
  INDEX `fk_PRESTADOR_PESSOA1_idx` (`PESSOA_ID_PESSOA` ASC),
  CONSTRAINT `fk_PRESTADOR_PESSOA1`
    FOREIGN KEY (`PESSOA_ID_PESSOA`)
    REFERENCES `mydb`.`PESSOA` (`ID_PESSOA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RECIBO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RECIBO` (
  `ID_RECIBO` INT(11) NOT NULL AUTO_INCREMENT,
  `VALOR` INT(11) NOT NULL,
  `DATA_EMISSAO` DATETIME NULL,
  `EMINENTE_ID_EMINENTE` INT(11) NOT NULL,
  `PRESTADOR_ID_PRESTADOR` INT(11) NOT NULL,
  PRIMARY KEY (`ID_RECIBO`, `EMINENTE_ID_EMINENTE`, `PRESTADOR_ID_PRESTADOR`),
  INDEX `fk_RECIBO_EMINENTE1_idx` (`EMINENTE_ID_EMINENTE` ASC),
  INDEX `fk_RECIBO_PRESTADOR1_idx` (`PRESTADOR_ID_PRESTADOR` ASC),
  CONSTRAINT `fk_RECIBO_EMINENTE1`
    FOREIGN KEY (`EMINENTE_ID_EMINENTE`)
    REFERENCES `mydb`.`EMINENTE` (`ID_EMINENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RECIBO_PRESTADOR1`
    FOREIGN KEY (`PRESTADOR_ID_PRESTADOR`)
    REFERENCES `mydb`.`PRESTADOR` (`ID_PRESTADOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UF` (
  `ID_UF` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME_UF` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`ID_UF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CIDADE` (
  `ID_CIDADE` INT(11) NOT NULL AUTO_INCREMENT,
  `UF_ID_UF` INT(11) NOT NULL,
  PRIMARY KEY (`ID_CIDADE`, `UF_ID_UF`),
  INDEX `fk_CIDADE_UF_idx` (`UF_ID_UF` ASC),
  CONSTRAINT `fk_CIDADE_UF`
    FOREIGN KEY (`UF_ID_UF`)
    REFERENCES `mydb`.`UF` (`ID_UF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ENDERECO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ENDERECO` (
  `ID_ENDERECO` INT(11) NOT NULL AUTO_INCREMENT,
  `TIPO_LOGRADOURO` VARCHAR(10) NOT NULL,
  `LOGRADOURO` VARCHAR(100) NOT NULL,
  `NUMERO` VARCHAR(10) NOT NULL,
  `COMPLEMENTO` VARCHAR(10) NOT NULL,
  `CEP` VARCHAR(8) NOT NULL,
  `TIPO` INT(11) NOT NULL,
  `CIDADE_ID_CIDADE` INT(11) NOT NULL,
  `CIDADE_UF_ID_UF` INT(11) NOT NULL,
  `PESSOA_ID_PESSOA` INT(11) NOT NULL,
  PRIMARY KEY (`ID_ENDERECO`, `CIDADE_ID_CIDADE`, `CIDADE_UF_ID_UF`, `PESSOA_ID_PESSOA`),
  INDEX `fk_ENDERECO_CIDADE1_idx` (`CIDADE_ID_CIDADE` ASC, `CIDADE_UF_ID_UF` ASC),
  INDEX `fk_ENDERECO_PESSOA1_idx` (`PESSOA_ID_PESSOA` ASC),
  CONSTRAINT `fk_ENDERECO_CIDADE1`
    FOREIGN KEY (`CIDADE_ID_CIDADE` , `CIDADE_UF_ID_UF`)
    REFERENCES `mydb`.`CIDADE` (`ID_CIDADE` , `UF_ID_UF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ENDERECO_PESSOA1`
    FOREIGN KEY (`PESSOA_ID_PESSOA`)
    REFERENCES `mydb`.`PESSOA` (`ID_PESSOA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

drop table UF;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;





-- Exercicio01
DESC UF;
INSERT INTO UF(NOME_UF) 
	values('AM'),
		  ('AP'),
		  ('BA'),
          ('CE'),
		  ('DF'),
		  ('ES'),
		  ('GO'),
		  ('MA'),
		  ('MG'),
		  ('MS'),
		  ('MT'),
		  ('PA'),
		  ('PB'),
		  ('PE'),
		  ('PI'),
          ('PR'),
          ('RJ'),
          ('RO'),
          ('RR'),
          ('RS'),
          ('SC'),
          ('SE'),
		  ('SP'),
		  ('TO'),
          ('RN'),
          ('AC'),
          ('AL');
SELECT * FROM UF;
-- Exercicio02 
DESC CIDADE;         
ALTER TABLE CIDADE ADD NOME varchar(45);

INSERT INTO CIDADE(UF_ID_UF,NOME)
	VALUES  (18,'Lunardeli'),
			(18,'Maringá'),
			(18,'Curitiba'),
            (18,'Apucarana'),
            (18,'Arapongas'),
            (18,'Ponta Grossa'),
            (18,'Jandaia do Sul'),
            (18,'Sertanopolis'),
			(18,'Cianorte'),
			(18,'Sarandi'),
            (18,'Londrina'),
            (18,'Cruzeiro do Oeste');

INSERT INTO CIDADE (UF_ID_UF,NOME)
	VALUES (25,'Ribeirão Preto'),
		   (25,'Cotia');

INSERT INTO CIDADE (UF_ID_UF,NOME)
	VALUES (26,'Tocantinopolis');
    
SELECT * FROM CIDADE;

DELETE UF FROM UF A LEFT OUTER JOIN CIDADE B ON A.UF_ID_UF = B.UF_ID_UF;